platform :ios, '8.0'
target ‘driverTerrace’ do

pod 'MBProgressHUD'
pod 'SDCycleScrollView','~> 1.73'
pod 'MJRefresh'
pod 'MJExtension'
pod 'AFNetworking'
pod 'IQKeyboardManager'
pod 'SDWebImage'
pod 'Masonry'
pod 'LYEmptyView'
pod 'HWDownSelectedView', '~> 1.0.1'
end
